baseURL = 'https://tea.xyz/'
languageCode = 'en-us'
title = 'Equitable Open-Source for Web3'

# menu links via config file

[menu]

  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    title = 'home'
    url = '/'
    weight = 1

  [[menu.main]]
    identifier = 'docs'
    name = 'Docs'
    title = 'docs'
    url = 'https://docs.tea.xyz'
    weight = 3

[security]
  [security.exec]
    allow = ['^go$', '^postcss$', '^npx$', '^babel$']
