baseURL = 'https://tea.xyz/'
languageCode = 'en-us'
title = 'Equitable Open-Source for Web3'

# menu links via config file

[menu]
  [[menu.main]]
    identifier = 'community'
    name = 'Community'
    title = 'community'
    url = './#community'
    weight = 4
  [[menu.main]]
    identifier = 'github'
    name = 'GitHub'
    title = 'github'
    url = 'https://github.com/teaxyz'
    weight = 6

[security]
  [security.exec]
    allow = ['^go$', '^postcss$', '^npx$', '^babel$']
